version: "3.5"

services:
  gateway:
    image: ivancuadros1988/img-gateway
    container_name: gateway-service
    restart: always
    ports:
    - 9000:8080
    networks:
    - aforo255
  security:
    image: ivancuadros1988/img-security
    container_name: security-service
    restart: always
    ports:
    - 9001:8080
    networks:
    - aforo255
  account:
    image: ivancuadros1988/img-account
    container_name: account-service
    restart: always
    ports:
    - 9002:8080
    networks:
    - aforo255
  deposit:
    image: ivancuadros1988/img-deposit
    container_name: deposit-service
    restart: always
    ports:
    - 9003:8080
    networks:
    - aforo255
  withdrawal:
    image: ivancuadros1988/img-withdrawal
    container_name: withdrawal-service
    restart: always
    ports:
    - 9004:8080
    networks:
    - aforo255
  history:
    image: ivancuadros1988/img-history
    container_name: history-service
    restart: always
    ports:
    - 9005:8080
    networks:
    - aforo255
  notification:
    image: ivancuadros1988/img-notification
    container_name: notification-service
    restart: always
    ports:
    - 9006:8080
    networks:
    - aforo255

networks:
  aforo255:
    name: micro